# Generated by Django 2.2.28 on 2026-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fotografia',
            field=models.ImageField(upload_to='contacto/'),
        ),
    ]
